<a href="https://colab.research.google.com/github/Jeffreyarukwe/DS4A_repo/blob/master/Project1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [15]:
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

In [16]:
%matplotlib inline 

In [17]:
dataset = pd.read_csv('iris.csv')
dataset.head()

sepal_length  sepal_width  petal_length  petal_width      species
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

In [ ]:
#boston = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/BostonHousing.csv')

In [39]:
class OrdinaryLeastSquares(object): 

  def __init__(self): 
    self.coefficients = []

  def fit(self, X, y): 
      if len(X.shape) == 1: X = self._reshape_x(x) 

      X = self._concatenate_ones(X)
      self.coefficients = np.linalg.inv(X.transpose().dot(X)).dot(X.transpose()).dot(y)

  def predict(self, entry): 
    b0 = self.coefficients[0]
    other_betas = self.coefficients[1:] 
    prediction = b0 

    for xi, bi in zip(entry, other_betas): 
      prediction += (bi * xi) 

      if prediction < 0.5: 
        output = 'Iris-setosa' 
      elif prediction >= 0.5 and prediction <= 1.5 : 
        output = 'Iris-versicolor'
      else: 
        output = 'Iris-virginica'

    return output

  def _reshape_x(self, X): 
      return X.reshape(-1, 1)

  def _concatenate_ones(self, X): 
      ones = np.ones(shape=X.shape[0]).reshape(-1, 1) 
      return np.concatenate((ones, X), 1) 



In [150]:
X = dataset.drop('species', axis=1).values 
y = dataset['species'].values
#y_original = dataset['species'].values

In [151]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(X, y, test_size = 1/3, random_state = 0)

In [154]:
y_original = y_test

In [133]:
#x_test = X[2*int(len(y)/3):] 
#x_train_data = dataset[:-int(len(y)/3)]

#y_test = y[2*int(len(y)/3):] 
#y_train_data = dataset[:-int(len(y)/3)]
#y_original = y[2*int(len(y)/3):] 

#y_train = y_train_data['species'].values
#x_train = x_train_data.drop('species', axis=1).values 


In [155]:
len(y_original)

50

In [156]:
from sklearn.preprocessing import LabelEncoder #Encoding the Dependent Variable
le = LabelEncoder()
y = le.fit_transform(y)
y_train = le.fit_transform(y_train)
y_test = le.fit_transform(y_test)

In [157]:
model = OrdinaryLeastSquares()

In [158]:
model.fit(x_train, y_train)

In [159]:
model.coefficients

array([ 2.71593637e-01, -1.57968347e-01, -1.70107959e-04,  2.40860931e-01,
        6.32930605e-01])

In [160]:
model.predict(x_test[0])

'Iris-virginica'

In [161]:
y_preds = []

for row in x_test: y_preds.append(model.predict(row)) 

In [162]:
pd.DataFrame({
    'Actual': y_original, 
    'Predicted': np.ravel(y_preds)
})

Actual        Predicted
0    Iris-virginica   Iris-virginica
1   Iris-versicolor  Iris-versicolor
2       Iris-setosa      Iris-setosa
3    Iris-virginica   Iris-virginica
4       Iris-setosa      Iris-setosa
5    Iris-virginica   Iris-virginica
6       Iris-setosa      Iris-setosa
7   Iris-versicolor  Iris-versicolor
8   Iris-versicolor  Iris-versicolor
9   Iris-versicolor  Iris-versicolor
10   Iris-virginica   Iris-virginica
11  Iris-versicolor  Iris-versicolor
12  Iris-versicolor  Iris-versicolor
13  Iris-versicolor  Iris-versicolor
14  Iris-versicolor  Iris-versicolor
15      Iris-setosa      Iris-setosa
16  Iris-versicolor  Iris-versicolor
17  Iris-versicolor  Iris-versicolor
18      Iris-setosa      Iris-setosa
19      Iris-setosa      Iris-setosa
20   Iris-virginica   Iris-virginica
21  Iris-versicolor  Iris-versicolor
22      Iris-setosa      Iris-setosa
23      Iris-setosa      Iris-setosa
24   Iris-virginica   Iris-virginica
25      Iris-setosa      Iris-setosa
26      Iris-setosa      Iris-setosa
27  Iris-versicolor  Iris-versicolor
28  Iris-versicolor  Iris-versicolor
29      Iris-setosa      Iris-setosa
30   Iris-virginica   Iris-virginica
31  Iris-versicolor  Iris-versicolor
32      Iris-setosa      Iris-setosa
33   Iris-virginica   Iris-virginica
34   Iris-virginica   Iris-virginica
35  Iris-versicolor  Iris-versicolor
36      Iris-setosa      Iris-setosa
37  Iris-versicolor   Iris-virginica
38  Iris-versicolor  Iris-versicolor
39  Iris-versicolor  Iris-versicolor
40   Iris-virginica   Iris-virginica
41      Iris-setosa      Iris-setosa
42   Iris-virginica   Iris-virginica
43      Iris-setosa      Iris-setosa
44      Iris-setosa      Iris-setosa
45  Iris-versicolor  Iris-versicolor
46   Iris-virginica   Iris-virginica
47   Iris-virginica   Iris-virginica
48   Iris-virginica  Iris-versicolor
49   Iris-virginica   Iris-virginica

In [163]:
num_correct = 0 
for i in range(len(y_preds)): 
    if y_preds[i] == y_original[i]: 
        num_correct += 1 

In [164]:
num_correct/len(y_preds) 

0.96

In [165]:
from sklearn import metrics

# Printing the confusion matrix
print(metrics.confusion_matrix(y_original, y_preds))

# Printing the precision and recall, among other metrics
print(metrics.classification_report(y_original, y_preds))

[[16  0  0]
 [ 0 18  1]
 [ 0  1 14]]
                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        16
Iris-versicolor       0.95      0.95      0.95        19
 Iris-virginica       0.93      0.93      0.93        15

       accuracy                           0.96        50
      macro avg       0.96      0.96      0.96        50
   weighted avg       0.96      0.96      0.96        50

